# V2
- hosts: all

  tasks:
  - name: "Installing web-server"
    package: 
      name: "httpd" 
      state: present

  - name: "Copying web.html"
    copy: 
      src: "/web.html"
      dest: "/var/www/html"

  - name: "Start web-server"
    service: 
      name: "httpd"
      state: started
      enabled: yes

  - name: "Setup firewall port"
    firewalld:
      immediate: yes
      port: "80/tcp" 
      state: enabled
      permanent: yes