# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html
- hosts: aws_control_node
  tasks:
  - name: Download docker.repo to configure yum for docker
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
    ansible.builtin.get_url:
      url: "https://download.docker.com/linux/centos/docker-ce.repo"
      dest: /etc/yum.repos.d/

  - name: Install docker-ce software
    ansible.builtin.package:
      name: "docker-ce"
      state: present

  - name: Start docker-ce
    ansible.builtin.service:
      name: "docker"
      state: started
      
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  - name: Ensure /var/www/html directory exists
    ansible.builtin.file:
      path: /var/www/html
      state: directory

  - name: "Copying web.html containg string rhel"
    copy: 
      src: "/web.html"
      dest: "/var/www/html"

  - name: "replacing rhel string with centos"
    replace:
      path: "/var/www/html/web.html"
      regexp: 'rhel'
      replace: 'centos'