- hosts: aws_control_node,local_control_node
  # Specifying variable file 
  vars_files:
  - vars.yml
  tasks:
    - name: install web package
      package:
        name: "{{ web_package }}" 
        state: present
      # Skip task when false
      # when: false
      # when: z == 6
    - debug:
            var : webpage

    - name: conf changes in my apache web web-server
      template: 
        dest: "/etc/httpd/conf.d/anand.conf"
        src: "web.conf.j2"
      notify: "restart web-server"

    - name: Deploy web package
      template:
        src: "{{ webpage }}"
        dest: "{{ web_doc_root }}/index.html"
    
    - name: Start web-server
      service:
        name: "{{ web_package }}"
        state: started
  # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html
  handlers:
    - name: restart web-server
      service:
        name: "{{ web_package }}"
        state: restarted